config/routes.rb
Rails.application.routes.draw do
  root 'posts#index' 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :posts
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Rails.application.routes.url_helpers
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      # Post to Facebook
      post_to_facebook(@post)
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :descriptions)
  end

  def post_to_facebook(post)
    user = post.user
    graph = Koala::Facebook::API.new(user.access_token)
    g =  graph.get_connections("me", "friends")
    graph.put_connections('me', 'feed', message: post.title, description: post.descriptions)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: [current_user, post] do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% post.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :descriptions %><br>
      <%= form.text_area :descriptions %><br>
      <% post.errors.full_messages_for(:descriptions).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% if current_user %>
  <h2>User Email: <%= current_user.email %></h2>
  <% if current_user.avatar_url.present? %>
    <%= image_tag(current_user.avatar_url)%><br><br>
  <% else %>
      <%= image_tag("users-vector-icon-png.jpg") %><br>
  <% end %>
  <%= button_to "Logout", destroy_user_session_path, data: {turbo: false}, method: :delete%><br>
<%else%>
  <%= link_to "Login", new_user_session_path %><br><br>
  <%= link_to "Create Account",new_user_registration_path %>
<%end%>


<%= link_to "New Post", new_user_post_path(current_user.id), class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.description %></p>

<ul>
  <li><%= link_to "Edit", edit_post_path(@post) %></li>
</ul>